SELECT
	ALL_SPECIALTY_SECTION = UAR_GET_CODE_DISPLAY(V.PARENT_EVENT_SET_CD)
	, FIRST_LEVEL_EVENT_SETS = UAR_GET_CODE_DISPLAY(V.EVENT_SET_CD)
	, L1_SEQ_NUM = V.EVENT_SET_COLLATING_SEQ
	, SECOND_LEVEL_EVENT_SETS = UAR_GET_CODE_DISPLAY(V2.EVENT_SET_CD)
	, L2_SEQ_NUM = V2.EVENT_SET_COLLATING_SEQ
	, THIRD_LEVEL_EVENT_SETS = UAR_GET_CODE_DISPLAY(V3.EVENT_SET_CD)
	, L3_SEQ_NUM = V3.EVENT_SET_COLLATING_SEQ

FROM
	V500_EVENT_SET_CANON   V
	, V500_EVENT_SET_CANON   V2
	, V500_EVENT_SET_CANON   V3

plan v WHERE V.PARENT_EVENT_SET_CD in (8918567) ;CHW ALL SPECIALTY SECTIONS - ;SCH ALLSPECSECT: 8918567
join v2 where v2.PARENT_EVENT_SET_CD = outerjoin(V.EVENT_SET_CD)
and v2.parent_event_set_cd not in (446580242, 8918574, 9027841); ClinicalDoc, Working View Sections, Advanced Care Docs
join v3 where v3.PARENT_EVENT_SET_CD = outerjoin(V2.EVENT_SET_CD)

ORDER BY
	ALL_SPECIALTY_SECTION
	, L1_SEQ_NUM
	, L2_SEQ_NUM
	, L3_SEQ_NUM

WITH NOCOUNTER, SEPARATOR=" ", FORMAT