;22/09/2017 - Javad Adeli
;This query displays all active discrn rules with Evoke details and Purpose if documented

SELECT
	RULE_NAME = EM.MODULE_NAME
	, EVOKE_DETAILS = EMS2.EKM_INFO	
	;, EMS.DATA_TYPE
	, PURPOSE = EMS.EKM_INFO
	;, EMS2.DATA_TYPE

FROM
	EKS_MODULE   EM
	, EKS_MODULESTORAGE   EMS
	, EKS_MODULESTORAGE   EMS2

PLAN EM WHERE EM.ACTIVE_FLAG = "A"
AND EM.MAINT_VALIDATION = "PRODUCTION"
JOIN EMS WHERE EMS.MODULE_NAME = EM.MODULE_NAME
AND EMS.VERSION = EM.VERSION
AND EMS.DATA_TYPE IN(1)
JOIN EMS2 WHERE EMS2.MODULE_NAME = EM.MODULE_NAME
AND EMS2.VERSION = EM.VERSION
AND EMS2.DATA_TYPE IN(7)

ORDER BY
	EM.MODULE_NAME

WITH NOCOUNTER, SEPARATOR=" ", FORMAT
